import { StyleSheet } from "react-native";

export const colors = {
  page: "#F6F8FB",
  surface: "#ffffff",
  soft: "#F8FAFC",
  mid: "#E8EEF3",
  line: "#D8DEE8",
  text: "#18212F",
  quiet: "#667085",
  blue: "#176B87",
  red: "#C2413A",
  green: "#12805C",
  amber: "#B76E00",
  dark: "#0F4F64",
};

export const wire = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.page,
    padding: 16,
  },
  canvas: {
    flex: 1,
    backgroundColor: colors.surface,
    minHeight: 520,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: "hidden",
  },
  title: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 12,
  },
  nav: {
    minHeight: 44,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 18,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  navText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.quiet,
  },
  navSpacer: {
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 22,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.text,
    marginBottom: 14,
  },
  button: {
    backgroundColor: colors.blue,
    paddingHorizontal: 22,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },
  buttonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  linkButtonText: {
    color: colors.blue,
    fontSize: 15,
    fontWeight: "700",
  },
  table: {
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: colors.surface,
  },
  row: {
    minHeight: 50,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  headerRow: {
    backgroundColor: colors.mid,
    minHeight: 56,
  },
  cell: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 13,
    color: colors.text,
  },
  formPanel: {
    alignSelf: "center",
    width: "62%",
    maxWidth: 360,
    minWidth: 280,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 20,
  },
  label: {
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 8,
  },
  input: {
    height: 42,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 6,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  deleteBox: {
    width: 28,
    height: 28,
    backgroundColor: colors.red,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    borderRadius: 6,
  },
  deleteText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 24,
  },
  editPill: {
    backgroundColor: colors.blue,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    borderRadius: 6,
  },
  editText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  pill: {
    backgroundColor: colors.mid,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  pillActive: {
    backgroundColor: colors.blue,
  },
  linkButton: {
    justifyContent: "center",
  },
  card: {
    backgroundColor: colors.surface,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    overflow: "hidden",
  },
  cardHead: {
    minHeight: 46,
    backgroundColor: colors.soft,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  cardBody: {
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  tinyBold: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  tiny: {
    fontSize: 12,
    color: colors.text,
  },
});
